CREATE DATABASE PRIMEIRAFORMA
GO

USE PRIMEIRAFORMA
GO

CREATE TABLE PESSOA(
     IDPESSOA INT NOT NULL PRIMARY KEY IDENTITY(1,1), --O ID PESSOA É UM INTEIRO NÃO NULO E QUE NÃO PODE RECEBER UM VALOR VAZIO.
	 NOME VARCHAR(100),                               --O IDENTITY É UM INCREMENTO QUE INICIA DE 1 OU ALGUM VALOR DEFINIDO E CONTA DE 1 EM 1 OU UM VALOR DEFINIDO
	 IDADE INT,                                --NO GERAL O IDENTITY INDICA QUE O ATRIBUTO EM QUESTÃO É O QUE VAI INICIAR A CONTAGEM.
	 SEXO CHAR(1),                                    
	 CPF VARCHAR(16) UNIQUE
)
GO
 
   
CREATE TABLE ENDERECO (
     IDENDERECO INT PRIMARY KEY IDENTITY,
	 CEP VARCHAR(9), 
     ENDERECO VARCHAR(45),
	 COMPLEMENTO VARCHAR(45), 
     CIDADE VARCHAR(27),  
     UF CHAR(2),
	 ID_PESSOA INT UNIQUE, --UNIQUE É UMA "CARDINALIDADE IMPLÍCITA" AQUI DIZ QUE UMA PESSOA NÃO PODE TER MAIS DE UM ENDEREÇO
	 
	 --CRIA UMA CHAVE ESTRANGEIRA DENOMINADA ID_PESSOA QUE FARÁ REFERÊNCIA, NA TABELA PESSOA, AO IDPESSOA.
	 CONSTRAINT FK_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
)
GO


CREATE TABLE TELEFONE (
     IDTELEFONE INT PRIMARY KEY IDENTITY,
	 TELEFONEFIXO VARCHAR(21), 
     TELEFONECELULAR VARCHAR(21), 
	 ID_PESSOA INT,

	 CONSTRAINT FK_ID_PESSOA_TELEFONE FOREIGN KEY (ID_PESSOA) REFERENCES PESSOA(IDPESSOA)
)
GO

--OS COMANDOS ABAIXO É RELEVANTE PARA CONSULTAS

SELECT NOME, CPF, CEP, ENDERECO --PROJETE O NOME, CPF, CEP E ENDERECO 
      FROM PESSOA --DA TABELA PESSOA
	  INNER JOIN ENDERECO --E JUNTE A TABELA PESSOA COM O ENDERECO
	  ON IDPESSOA = ID_PESSOA --ONDE A CHAVE PRIMÁRIA(IDPESSOA) SEJA IGUAL A CHAVE ESTRANGEIRA(ID_PESSOA)
	  WHERE SEXO = 'F'--E O SEXO SEJA FEMININO
GO



SELECT P.NOME, P.IDADE, P.CPF, E.CEP, E.UF, T.TELEFONECELULAR FROM PESSOA P  --USANDO UM ALIAS(APELIDO) PARA FAZER A JUNÇAO DE VÁRIAS TABELAS ALIAS = PESSOA P; TELEFONE T; ENDERECO E, ETC.
	  INNER JOIN ENDERECO E ON IDPESSOA = E.ID_PESSOA
	  INNER JOIN TELEFONE T ON IDPESSOA = T.ID_PESSOA
	  WHERE SEXO = 'F'
GO



SELECT P.NOME, P.CPF, T.TELEFONECELULAR, E.CEP, E.UF FROM PESSOA P --MOSTRA TUDO A ESTÁ A ESQUERDA E A DIREITA
	  LEFT JOIN TELEFONE T ON P.IDPESSOA = T.ID_PESSOA
	  INNER JOIN ENDERECO E ON P.IDPESSOA = E.ID_PESSOA
GO

SELECT P.NOME, P.CPF, T.TELEFONECELULAR, E.CEP, E.UF FROM PESSOA P --NÃO MOSTRA NOMES QUE TEM ATRIBUTOS NULOS
	  RIGHT JOIN TELEFONE T ON P.IDPESSOA = T.ID_PESSOA
	  INNER JOIN ENDERECO E ON P.IDPESSOA = E.ID_PESSOA
GO

SELECT P.NOME, P.CPF, T.TELEFONECELULAR, E.CEP, E.UF FROM PESSOA P -- MOSTRA TUDO
	  FULL JOIN TELEFONE T ON P.IDPESSOA = T.ID_PESSOA
	  INNER JOIN ENDERECO E ON P.IDPESSOA = E.ID_PESSOA
GO


SELECT P.NOME, P.CPF, ISNULL(T.TELEFONECELULAR,'NÃO CADASTRADO') AS 'TELEFONE CELULAR', E.CEP, E.UF FROM PESSOA P --ISNULL SIGNIFICA QUE SE FOR NULO VAI IMPRIMIR A MSG EDITADA
	  LEFT JOIN TELEFONE T ON P.IDPESSOA = T.ID_PESSOA
	  INNER JOIN ENDERECO E ON P.IDPESSOA = E.ID_PESSOA
GO

ALTER TABLE TELEFONE ADD CONSTRAINT CK_TELEFONE CHECK(TIPOTELEFONE IN('RESIDENCIAL', 'CELULAR', 'CORPORATIVO'))--VERIFICA SE NA TABELA TELEFONE O TIPO DE TELEFONE ESTÁ RECEBENDO PELO MENOS ALGUM DOS VALORES INFORMADOS
GO





CREATE TABLE PRODUTO(

     IDPRODUTO INT PRIMARY KEY IDENTITY(1,1),
	 NOMEPRODUTO VARCHAR(30),
	 QUANTIDADE INT,
	 PRECOUNITARIO MONEY

)
GO

  
SELECT NOMEPRODUTO AS 'DESCRIÇÃO', --SELECIONA OS NOMES DOS PRODUTOS NUMA COLUNA CHAMADA DESCRIÇÃO,
       QUANTIDADE AS 'QUANTIDADE', --QUANTIDADE NUMA COLUNA QUANTIDADE,
	   PRECOUNITARIO AS 'VALOR',   --VALOR NUMA COLUNA VALOR E
	   (QUANTIDADE * PRECOUNITARIO) AS 'SUBTOTAL' --CALCULA O SUB TOTAL FAZENDO UMA MULTIPLICAÇÃO E RETORNA O VALOR NUMA COLUNA DENOMINDADA SUBTOTAL.
	   FROM PRODUTO
GO










--DATAS NO SQL

SELECT GETDATE() --MOSTRA A DATA NO FORMATO ANO MÊS E DIA, MOSTRA AS HORAS, MINUTOS, SEGUNDOS E MILISEGUNDOS.
GO

SELECT DATEDIFF(YEAR, '1998-02-25', GETDATE()) AS IDADE --CALCULA UMA DATA E IMPRIME NUMA TABELA CHAMADA IDADE.
GO

SELECT (DATEDIFF(DAY, '1998-02-25', GETDATE()) / 365) AS IDADE  --CALCULA A DATA E RETORNA O VALOR DIVIDIDO POR 365.
GO

SELECT DATENAME(MONTH, '1998-02-25') --RETORNA O MÊS DA DATA INFORMADA POR EXTENSO
GO


SELECT DATENAME(WEEKDAY, '1998-02-25') AS DIA_DA_SEMANA --RETORNA O DIA DA SEMANA DA DATA INFORMADA POR EXTENSO NUMA COLUNA CHAMADA DIA DA SEMANA
GO

SELECT DATEPART(WEEKDAY, '1998-02-25') --RETORNA O DIA DA SEMANA DA DATA INFORMADA EM NÚMERO INTEIRO.
GO

SELECT DATEADD(DAY, 24, GETDATE())--IMORIME A DATA DE HOJE SOMADAS COM 24 DIAS
GO


--RASCUNHO DE ADIÇÃO DE DADOS
INSERT INTO ENDERECO VALUES('74936-230','Rua H 72', 'Cidade Vera Cruz', 'Aparecida de Goiânia', 'GO', 5) --O NÚMERO 6 É O NÚMERO DO ID DA TERCEIRA PESSOA, O QUAL O ENDREÇO É INSERIDO.
GO

INSERT INTO PESSOA VALUES('Priscilla Fonseca Claudino', 21, 'F', '332.362.531-50')
GO

INSERT INTO TELEFONE VALUES('(89) 3211-8621', '(86) 97262-5921', 2)
GO

INSERT INTO PRODUTO VALUES('IPHONE 963', 9, '18000.18')
GO


SP_HELP PESSOA
GO


SELECT *FROM PESSOA
GO

SELECT *FROM ENDERECO
GO

SELECT *FROM TELEFONE
GO


SELECT *FROM PRODUTO
GO

DELETE FROM PESSOA WHERE NOME = 'SUENIA BAESSO SOARES '
GO
--FIM
