CREATE DATABASE FICHAMEDICA
GO

USE FICHAMEDICA
GO

CREATE TABLE PACIENTE(
     IDPACIENTE BIGINT PRIMARY KEY IDENTITY(36,3),
	 NOME VARCHAR(50),
	 IDADE INT,
	 SEXO CHAR(1),
	 RG VARCHAR(9) UNIQUE,
	 CPF VARCHAR(16) UNIQUE, 
     DTNASC VARCHAR(10)
)
GO

CREATE TABLE ENDERECO(
     IDENDERECO BIGINT PRIMARY KEY IDENTITY(72,6),
     CEP VARCHAR(12),
     ENDERECO VARCHAR(54),
	 COMPLEMENTO VARCHAR(36),
     CIDADE VARCHAR(27),
	 ESTDADO VARCHAR(18),
     UF CHAR(2),

	 ID_PACIENTE BIGINT UNIQUE,
	 CONSTRAINT FK_ID_PACIENTE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE)

)
GO

CREATE TABLE TELEFONE(
     IDTELEFONE BIGINT PRIMARY KEY IDENTITY(63,9),
     CELULAR VARCHAR(18),
     TELEFONEFIXO VARCHAR(15),

     ID_PACIENTE BIGINT,
	 CONSTRAINT FK_ID_PACIENTE_TELEFONE FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE)
)
GO

CREATE TABLE CONVENIO(
     IDCONVENIO BIGINT PRIMARY KEY IDENTITY(27,12),
     TIPO VARCHAR(36),
	 SITUACAO VARCHAR(27),

	 ID_PACIENTE BIGINT UNIQUE,
	 CONSTRAINT FK_ID_PACIENTE_CONVENIO FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE)

)
GO

CREATE TABLE CONSULTA (
     IDCONSULTA BIGINT PRIMARY KEY IDENTITY(63,27),
     DTCONS VARCHAR(10),
     DESCRICAO TEXT,

	 ID_PACIENTE BIGINT,
	 CONSTRAINT FK_ID_PACIENTE_CONSULTA FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE)

)
GO

CREATE TABLE MEDICO (
     MATRICULA BIGINT PRIMARY KEY IDENTITY(27,9),
	 CRM VARCHAR(9) UNIQUE,
     NOME VARCHAR(50),
     ESPECIALIZACAO varchar(80),

	 ID_PACIENTE BIGINT,
	 CONSTRAINT FK_ID_PACIENTE_MEDICO FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE)

)
GO

CREATE TABLE EXAME (
     IDEXAME INT PRIMARY KEY IDENTITY (72,3),
     NOME VARCHAR(50),
     DTEXAME VARCHAR(10),

	 ID_PACIENTE BIGINT,
	 CONSTRAINT FK_ID_PACIENTE_EXAME FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(IDPACIENTE)

)
GO


SELECT P.NOME, P.IDADE, P.CPF, P.DTNASC, E.CEP, E.ENDERECO, E.UF, T.CELULAR, C.TIPO, C.SITUACAO,
       CC.DTCONS, CC.DESCRICAO, M.NOME, M.CRM, M.ESPECIALIZACAO, EX.NOME, EX.DTEXAME FROM PACIENTE P

INNER JOIN ENDERECO E ON IDPACIENTE = E.ID_PACIENTE
INNER JOIN TELEFONE T ON IDPACIENTE = T.ID_PACIENTE
INNER JOIN CONVENIO C ON IDPACIENTE = C.ID_PACIENTE
INNER JOIN CONSULTA CC ON IDPACIENTE = CC.ID_PACIENTE
INNER JOIN MEDICO M ON IDPACIENTE = M.ID_PACIENTE
INNER JOIN EXAME EX ON IDPACIENTE = EX.ID_PACIENTE

WHERE SEXO = 'F'

GO

SP_HELP PACIENTE
GO

SELECT *FROM PACIENTE
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO PACIENTE VALUES('Alexandre Loureiro Portugal', 19, 'M', '4.787.335', '324.615.858-49', '06/09/2003')
GO


SP_HELP ENDERECO
GO

SELECT *FROM ENDERECO
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO ENDERECO VALUES('68911-031', 'Rua Rio Gurijuba', 'Fazendinha', 'Macapá', 'AP',60)
GO

ALTER TABLE ENDERECO DROP COLUMN ESTDADO
GO



SP_HELP TELEFONE
GO

SELECT *FROM TELEFONE
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO TELEFONE VALUES('(89) 99476-8767', '(89) 3685-1148',60)
GO

ALTER TABLE ENDERECO DROP COLUMN ESTDADO
GO

SP_HELP CONVENIO
GO

SELECT *FROM CONVENIO
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO CONVENIO VALUES('Empresarial ', 'BLOQUEADO',60)
GO

ALTER TABLE ENDERECO DROP COLUMN ESTDADO
GO

SP_HELP CONSULTA
GO

SELECT *FROM CONSULTA
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO CONSULTA VALUES('10/09/2032', 'SOLICITA AO MEDICO DA ESPECIALIDADE TAL, O EXAME TAL, COM URGENCIA TAL, ANTES DE TAL DIA',60)
GO

ALTER TABLE ENDERECO DROP COLUMN ESTDADO
GO

SP_HELP MEDICO
GO

SELECT *FROM MEDICO
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO MEDICO VALUES('3333', 'Paula Carino Cormack', 'CORAÇÃOZISTA',60)
GO

ALTER TABLE ENDERECO DROP COLUMN ESTDADO
GO

SP_HELP EXAME
GO

SELECT *FROM EXAME
GO

DELETE FROM PACIENTE WHERE NOME = 'JÚLIO NEVES TORRES '
GO

INSERT INTO EXAME VALUES('CORAÇÃO', '04/06/2029',60)
GO

ALTER TABLE ENDERECO DROP COLUMN ESTDADO
GO
